- name: Copy Mongo Repo
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repos.d/mongo.repo

- name: Install MondoDB
  ansible.builtin.dnf:
   name: mongodb-org
   state: present

- name: Allow Remote connections
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'

- name: Enable and start MongoDB
  ansible.builtin.service:
   name: mongod
   state: restarted
   enabled: true